# Generated by Django 2.1.1 on 2018-09-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
